version: "3.8"

services:
  # Jenkins controller
  jenkins:
    build: ./jenkins
    image: jenkins-secure:latest
    container_name: jenkins
    ports:
      - "8080:8080"    # Jenkins UI
      - "50000:50000"  # Jenkins agent port
    # environment:
    #   - DOCKER_HOST=tcp://docker:2375
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Mount host Docker socket
    networks:
      - jenkins_net

  # BloodHound
  bloodhound:
    image: specterops/bloodhound:latest
    depends_on:
      - bloodhound-db
      - bloodhound-graph-db
    ports:
      - "127.0.0.1:8081:8080"   # BloodHound UI
    networks:
      - jenkins_net

  bloodhound-db:
    image: postgres:16
    environment:
      POSTGRES_USER: blood
      POSTGRES_PASSWORD: blood
      POSTGRES_DB: blood
    networks:
      - jenkins_net

  bloodhound-graph-db:
    image: neo4j:4.4
    environment:
      NEO4J_AUTH: neo4j/blood
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - jenkins_net

volumes:
  jenkins_home: {}

networks:
  jenkins_net:
    driver: bridge
