version: "3.8"

services:
  # Docker-in-Docker for Jenkins
  dind:
    image: docker:24-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    volumes:
      - docker_layer_cache:/var/lib/docker
    networks:
      - jenkins_net

  # Jenkins controller
  jenkins:
  build: ./jenkins
  image: jenkins-secure:dind
  privileged: true
  depends_on:
    - dind
  ports:
    - "8080:8080"
    - "50000:50000"
  environment:
    - DOCKER_HOST=tcp://dind:2375
    - DOCKER_TLS_VERIFY=0
  volumes:
    - jenkins_home:/var/jenkins_home
  networks:
    - jenkins_net


  # BloodHound
  bloodhound:
    image: specterops/bloodhound:latest
    depends_on:
      - bloodhound-db
      - bloodhound-graph-db
    ports:
      - "127.0.0.1:8081:8080"   # BloodHound UI on host 8081
    networks:
      - jenkins_net

  bloodhound-db:
    image: postgres:16
    environment:
      POSTGRES_USER: blood
      POSTGRES_PASSWORD: blood
      POSTGRES_DB: blood
    networks:
      - jenkins_net

  bloodhound-graph-db:
    image: neo4j:4.4
    environment:
      NEO4J_AUTH: neo4j/blood
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - jenkins_net

volumes:
  jenkins_home: {}
  docker_layer_cache: {}

networks:
  jenkins_net:
    driver: bridge
